services:
  app:
    container_name: soft-app
    build:
      context: ./soft
      dockerfile: Dockerfile.dev

    working_dir: /app

    volumes:
      - ./soft:/app
      - /app/node_modules

    command: npm run dev

    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
      CHOKIDAR_INTERVAL: "100"

    ports:
      - "3000:3000"